# Start with a Python 3.7 base image
FROM python:3.8


# Set up Node.js
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - \
    && apt-get install -y nodejs

# Add PyTorch to Node's Python path  
ENV NODE_PATH="/usr/local/lib/python3.7/site-packages:${NODE_PATH}"

# Set environment variables (optional)
ARG MONGODB_URI
ARG NODE_ENV
ARG PORT
ARG SMTP_USERNAME
ARG GMAIL_PASSWORD
ARG SMTP_PASSWORD
ARG KMP_DUPLICATE_LIB_OK
ARG SMTP_PORT
ARG SMTP_SERVER

ENV MONGODB_URI=$MONGODB_URI
ENV NODE_ENV=$NODE_ENV
ENV PORT=$PORT
ENV SMTP_USERNAME=$SMTP_USERNAME
ENV GMAIL_PASSWORD=$GMAIL_PASSWORD
ENV SMTP_PASSWORD=$SMTP_PASSWORD
ENV KMP_DUPLICATE_LIB_OK=$KMP_DUPLICATE_LIB_OK
ENV SMTP_PORT=$SMTP_PORT
ENV SMTP_SERVER=$SMTP_SERVER

# Copy Python requirements
COPY ./requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

# Copy Node.js app code
COPY package.json /app/
WORKDIR /app
COPY ./ /app
RUN npm install

# Run the Node.js app
CMD ["node", "server.js"]
