version: "3"
services:

  app:
    image: ginkgo_backend_image
    container_name: ginkgo_backend_container
    build:
      context: .
      args:
        NODE_ENV: $NODE_ENV
        PORT: $PORT     
    env_file: 
     - .env
    ports:
     - "$PORT:$PORT"
    command: ["node", "server.js"]